import { ResponseRecruitment } from "@/types/api/recruitment";

const RECRUITMENT: ResponseRecruitment = {
  recruitment: [
    {
      id: 1,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 2,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 3,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 4,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 5,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 6,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 7,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 8,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 9,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
    {
      id: 10,
      serviceType: "산업기능요원",
      experienceLevel: "경력무관",
      educationLevel: "대학졸업",
      expirationDate: "채용시 마감",
      title: "머신러닝 엔지니어 채용",
      company: "샌드버드",
      location: "경기도 성남시",
      salary: "8000~9000만원",
      href: "https://www.google.com",
    },
  ],
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);

  const serviceType = searchParams.get("service_type");

  return Response.json(RECRUITMENT);
}
